import type uWS from 'uWebSockets.js';
import type { RecognizedString } from 'uWebSockets.js';
import { EventEmitter } from 'node:events';
import { type ReadStream } from 'node:fs';
import { type BrotliCompress, type BrotliOptions, type Deflate, type Gzip, type ZlibOptions } from 'node:zlib';
import type { INanoexpressOptions } from '../../types/nanoexpress';
import { resAbortHandler, resAbortHandlerExpose, resConfig, resCorkHandlers, resCorkIsCorked, resEvents, resHeaders, request as resRequest, response as resResponse } from '../constants';
import type HttpRequest from './http-request';
declare class HttpResponse {
    [resRequest]: HttpRequest | null;
    [resResponse]: uWS.HttpResponse | null;
    protected [resHeaders]: Record<string, RecognizedString | null> | null;
    protected [resAbortHandler]: (() => void)[];
    protected [resCorkHandlers]: (() => void)[];
    protected [resAbortHandlerExpose]: boolean;
    protected [resCorkIsCorked]: boolean;
    protected [resConfig]: INanoexpressOptions;
    protected [resEvents]: EventEmitter | null;
    done: boolean;
    aborted: boolean;
    streaming: boolean;
    protected _headersSet: boolean;
    protected registered: boolean;
    protected mode: 'immediate' | 'queue' | 'cork';
    serialize?: (data: Record<string, unknown> | string | number | boolean) => string;
    compiledResponse?: string;
    statusCode: number;
    id: number;
    constructor(config: INanoexpressOptions);
    protected registerEvents(): this;
    on(eventName: string | symbol, eventArgument: (eventArg?: unknown) => void): this;
    once(eventName: string | symbol, eventArgument: (eventArg?: unknown) => void): this;
    off(eventName: string | symbol, eventArgument: (eventArg?: unknown) => void): this;
    removeListener(eventName: string | symbol, eventArgument: (eventArg?: unknown) => void): this;
    emit(eventName: string | symbol, eventArgument?: never): boolean;
    setResponse(res: uWS.HttpResponse, req: HttpRequest): this;
    cork(callback: () => void): this;
    end(body?: uWS.RecognizedString, closeConnection?: boolean): this;
    sse(body: ReadStream): this;
    protected _sse(body: ReadStream): this;
    protected _end(body?: uWS.RecognizedString, closeConnection?: boolean): this;
    status(code: number): this;
    writeHead(code: number | Record<string, RecognizedString> | undefined, headers?: Record<string, RecognizedString>): this;
    redirect(code: number | string, path?: string): this;
    sendStatus(code: number): this;
    send(data: Record<string, unknown> | string | number | boolean, closeConnection?: boolean): this;
    pipe(stream: ReadStream, size?: number, compressed?: boolean): this;
    stream(stream: ReadStream, size?: number, compressed?: boolean): this;
    protected _stream(stream: ReadStream, size?: number, compressed?: boolean): this;
    compressStream(stream: ReadStream, options?: BrotliOptions | ZlibOptions, priority?: string[]): BrotliCompress | Gzip | Deflate | null;
    sendFile(path: string, lastModified?: boolean, compressed?: boolean): this;
    write(chunk: uWS.RecognizedString | ArrayBuffer): this;
    exposeAborted(): this;
    onAborted(handler: () => void): this;
    getHeader(key: string): RecognizedString | null;
    hasHeader(key: string): boolean;
    setHeader(key: string, rawValue: uWS.RecognizedString | number): this;
    set(key: string, value: uWS.RecognizedString): this;
    setHeaders(headers: Record<string, uWS.RecognizedString>): this;
    removeHeader(key: string): this;
    type(contentType: string): this;
}
export default HttpResponse;
//# sourceMappingURL=http-response.d.ts.map